### ISSUE TITLE
adding part (file) of entire gist

### ISSUE THREAD

**Issue by wiesehahn** [sellorm/quarto-social-embeds#5]
thanks for this extension!

It seems it is only possible to add the entire gist, however there are gists with multiple files in which case it would be nice to have the ability to add files individually. 

e.g. this works (adding both included files)
`{{< gist wiesehahn 6b6c215c227341f4faab03ff96fa7f1b >}}`

but this does not work (adding only one file)
`{{< gist wiesehahn 6b6c215c227341f4faab03ff96fa7f1b#file-lidar_availability_germany_table-md >}}`

Is it already possible somehow or would it be possible to add this functionality?

**Comment by sellorm** [comment]
It's not currently possible due to the way the extension generates the gist URL.

It should be possible to add such functionality though. I'll try and have a look sometime this week.

**Comment by sellorm** [comment]
Actually, I completely misspoke!

This functionality has been there since I wrote the gist handler, it's just not properly documented.

try:

```
{{< gist wiesehahn 6b6c215c227341f4faab03ff96fa7f1b lidar_availability_germany_table.md >}}
```

The optional 3rd parameter allows you to specify a filename, so it should just work

**Comment by wiesehahn** [comment]
Thanks, works as expected!

**Comment by sellorm** [comment]
Good to hear.
I've updated the documentation to include this use case too.
