### ISSUE TITLE
Mastodon don't show up

### ISSUE THREAD

**Issue by philkleer** [sellorm/quarto-social-embeds#6]
Hey everyone, 

I found your quarto extension and I love it. However, mastodon embedding didn't work for me in presentations. From `mastodon.lua`, I simple deleted `height:0` in the first `<div>`, then mastodon-toots showed up in both formats. Additionally, I deleted the large padding and the fixed height in iframe.

All the best
Phil

**Comment by ikashnitsky** [comment]
@bpkleer  Thank you so much for this comment, it really helped me a lot. 

@sellorm please consider changing `mastodon.lua` accordingly, please remove `padding-bottom: 56.25%; height: 0;` from the line 6. Otherwise it's impossible to arrange any elements after the embedded post.

**Comment by sellorm** [comment]
Thanks both, much appreciated!

PR merged.
